# Use root/example as user/password credentials
version: '3.0'

services:

  mysql:
    image: mysql:8.0.29
    restart: always

    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    # (this is just an example, not intended to be a production configuration)
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d
    ports:
      - "13306:3306"

  redis:
    image: redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    ports:
      - '16379:6379'